platform :ios, '8.0'

target 'Reactive Demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Reactive Demo
pod 'ReactiveCocoa', '~> 2.5'

end
