platform :ios, '8.0'

target 'Reactive Demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Reactive Demo
  pod 'ReactiveCocoa', '~> 2.5'
  
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'Masonry'
  pod 'Toast', '~> 3.0'
  pod 'MJRefresh'
end
